version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: